[[sectors]]
# Sector D
points = [
    [0, 1],
    [0, 6],
    [1, 7],
    [5, 7],
    [6, 6],
    [6, 4],
    [5, 3],
    [5, 1],
    [4, 0],
    [1, 0]
]
color=[255,0,0]
floor=0
ceil=1

[[sectors]]
# Sector A
points = [
    [0, 9],
    [0, 14],
    [1, 15],
    [5, 15],
    [6, 14],
    [6, 12],
    [5, 11],
    [5, 9],
    [4, 8],
    [1, 8]
]
color=[255,0,0]
floor=0
ceil=1

[[sectors]]
# Sector B
points = [
    [6, 12],
    [6, 14],
    [7, 14],
    [7, 12]
]
color=[0,255,0]
floor=0
ceil=0.9

[[sectors]]
# Sector E
points = [
    [6, 4],
    [6, 6],
    [7, 6],
    [7, 4]
]
color=[0,255,0]
floor=0
ceil=0.9

[[sectors]]
# Sector C
points = [
    [10, 15],
    [10, 9],
    [10, 7],
    [10, 3],
    [9, 2],
    [8, 2],
    [7, 3],
    [7, 4],
    [7, 6],
    [7, 12],
    [7, 14],
    [7, 17],
    [8, 18],
    [13, 18],
    [14, 17],
    [14, 16],
    [13, 15],
]
color=[0,0,255]
floor=0
ceil=1

[[sectors]]
# Sector F
points = [
    [10, 7],
    [10, 9],
    [11, 9],
    [11, 7]
]
color=[0,255,0]
floor=0
ceil=0.9

[[sectors]]
# Sector G
points = [
    [11, 5],
    [11, 7],
    [11, 9],
    [11, 12],
    [12, 12],
    [13, 12],
    [14, 12],
    [14, 4],
    [12, 4]
]
color=[255,0,0]
floor=0
ceil=2

[[sectors]]
# Sector H
points = [
    [11, 12],
    [11, 13],
    [12, 14],
    [12, 12]
]
color=[255,51,0]
floor=0.2
ceil=2

[[sectors]]
# Sector I
points = [
    [12, 12],
    [12, 14],
    [13, 14],
    [13, 12]
]
color=[255,102,0]
floor=0.4
ceil=2

[[sectors]]
# Sector J
points = [
    [13, 12],
    [13, 14],
    [14, 14],
    [14, 12]
]
color=[255,153,0]
floor=0.6
ceil=2

[[sectors]]
# Sector K
points = [
    [14, 12],
    [14, 14],
    [15, 14],
    [15, 12]
]
color=[255,204,0]
floor=0.8
ceil=2

[[sectors]]
# Sector L
points = [
    [15, 12],
    [15, 14],
    [16, 13],
    [16, 5],
    [15, 4],
    [14, 4],
    [14, 12],
]
color=[255,255,0]
floor=1
ceil=2
